### ISSUE TITLE
horizontalScroll

### ISSUE THREAD

**Issue by renatocava** [daattali/timevis#104]
Hi,

I am trying to add the horizontalScroll option but I am not successful, do you know if it is possible? have you tried it?

![image](https://user-images.githubusercontent.com/33307480/102733804-37d05200-430c-11eb-8f79-0b0811567d88.png)

https://visjs.github.io/vis-timeline/docs/timeline/#Configuration_Options

Thanks!

**Comment by daattali** [comment]
Usually when a parameter doesn't seem to work, it's because the version of visjs used in this package doesn't yet have that parameter implemented. This package is using a 4 year old version of visjs (because of various issues I still can't update to a newer one but I would love to at some point, see #50 for context) so you'll have to find the documentation of visjs for that version and see if it had this parameter.

**Comment by daattali** [comment]
This should now work if you use the latest timevis version from github.

```
timevis(
  data.frame(
    id = 1:2,
    content = c("one", "two"),
    start = c("2020-01-10", "2020-01-11")
  ), 
  options = list(horizontalScroll = TRUE, zoomable = FALSE)
)
```
