### ISSUE TITLE
Set different 'align' for each item is not allowed

### ISSUE THREAD

**Issue by Cheng-Cheng2** [daattali/timevis#106]
I could not figure out how to set 'align' for each item. Can only set the global option for boxes to align but not able to align differently for each item. However, this functionality is supported in the vis.js.

**Comment by daattali** [comment]
Usually when a parameter doesn't seem to work, it's because the version of visjs used in this package doesn't yet have that parameter implemented. This package is using a 4 year old version of visjs (because of various issues I still can't update to a newer one but I would love to at some point, see #50 for context) so you'll have to find the documentation of visjs for that version and see if it had this parameter.

**Comment by daattali** [comment]
visjs has been updated so this should work now with the latest github version 

```
timevis(
  data.frame(
    id = 1:3,
    content = c("one", "two", "three"),
    start = c("2020-01-10", "2020-01-11", "2020-01-12"),
    align = c("left", "right", "center")
  )
)
```
