### ISSUE TITLE
Cyrilic labels ???

### ISSUE THREAD

**Issue by iztokstotl** [daattali/timevis#122]
I have tried to use timevis.

When I try to run default timevis(), I get this result ...

![slika](https://user-images.githubusercontent.com/11088416/185745395-6b95253b-65f9-46de-9a16-425ea7ee5be0.png)

Cyrilic is drawn also in other examples ???

How can I solve this ?

**Comment by iztokstotl** [comment]
```
Sys.getlocale (category = "LC_ALL")

[1] "LC_CTYPE=sl_SI.UTF-8;LC_NUMERIC=C;LC_TIME=sl_SI.UTF-8;LC_COLLATE=sl_SI.UTF-8;LC_MONETARY=sl_SI.UTF-8;LC_MESSAGES=sl_SI.UTF-8;LC_PAPER=sl_SI.UTF-8;LC_NAME=C;LC_ADDRESS=C;LC_TELEPHONE=C;LC_MEASUREMENT=sl_SI.UTF-8;LC_IDENTIFICATION=C"
```

**Comment by iztokstotl** [comment]
`data <- data.frame(
  id      = 1:4,
  content = c("Item one"  , "Item two"  ,"Ranged item", "Item four"),
  start   = c("2016-01-10", "2017-01-11", "2018-01-20", "2016-02-14 15:00:00"),
  end     = c(NA          ,           NA, "2018-02-04", NA)
)

timevis(data)`

![slika](https://user-images.githubusercontent.com/11088416/185749039-43a9228c-6f0d-4dcc-8c14-584137da156d.png)

**Comment by daattali** [comment]
That is strange. I can only guess that it's due to some locale settings in your browser or system. This very likely has nothing to do with the R package and is controllable by the javascript. I would suggest looking in https://visjs.github.io/vis-timeline/docs/timeline/ to see if there's some way to change the locale.

**Comment by iztokstotl** [comment]
I have solved it with:

`  setOptions(list (locale = c("en"))`

**Comment by daattali** [comment]
That does mean that your browser for some reason doesn't default to english

**Comment by iztokstotl** [comment]
I am not sure, because the plots from ggplot2 don't have this problem when I use default setup.

**Comment by daattali** [comment]
That isn't indicative of much, because ggplot has nothing to do with the jacasxript library that runs timevis.

If you look at the documentation for the javascript library (https://visjs.github.io/vis-timeline/docs/timeline/), you can try running one of their simple examples on your machine ans see if it defaults to Cyrillic.

**Comment by daattali** [comment]
I'm closing this issue because I don't think it is related to the R package. If you find out that the javascript library works correctly but the R package does not, feel free to re-open.
