### ISSUE TITLE
Why "content "can't use javascript?

### ISSUE THREAD

**Issue by LiPingjiang** [daattali/timevis#129]
I used to put javascript in "content" to display information, but after I upgraded some packages, I found out that it doesn't work any more. Here's the code, the js after "href" is lost:

dt <- data.frame(
  id      = 1:4,
  content = c("Item one"  , "Item two"  ,"<a href=\"javascript:void(alert('Warning!!!'))\">click</a>", "Item four"),
  start   = c("2016-01-10", "2016-01-11", "2016-01-20", "2016-02-14 15:00:00"),
  end     = c(NA          ,           NA, "2016-02-04", NA)
)
timevis(dt)

![image](https://user-images.githubusercontent.com/11030498/219052109-6a392601-9db3-4d00-9052-fa1673b1a92b.png)

Thanks.

**Comment by daattali** [comment]
I never knew that running javascript inside the content ever worked. That is considered a big security risk, so even if you told me that it's possible, I would have assumed that at some point it would stop being possible. 

My guess it that the author of the underlying javascript library (visjs timeline) removed the ability to run arbitrary javascript on purpose, as a security fix. It's considered extremely dangerous to allow running javascript on the user's browser. When timevis updated, it also used a newer version of visjs timeline, and it probably had this security fix.

I'm closing this issue for now assuming that my guess about it being a security fix is correct.

**If my guess is wrong and you can show me a reprex of running javascript inside 'content' in the newest version of visjs timeline, then that means the issue is with {timevis}, and I'll reopen the issue and investigate.
