### ISSUE TITLE
Enhancement Request: title to include HTML code

### ISSUE THREAD

**Issue by pssguy** [daattali/timevis#2]
Not clear whether this is achievable, but it would make it more useful as a tooltip

**Comment by daattali** [comment]
This is not supported in HTML. The title is the same as when you add a `title` attribute to an anchor element or to any other HTML element - it's simply a simple way to show tooltip native to the browser. It only supports plain text.  In order to show HTML inside a tooltip you have to use some other special javascript library that builds tooltips not using a browser's native tooltip

**Comment by pssguy** [comment]
OK. Thought that was likely. Thanks for swift response
