### ISSUE TITLE
Label text: does not bleed over

### ISSUE THREAD

**Issue by briglass** [daattali/timevis#27]
![timevis_bleed](https://cloud.githubusercontent.com/assets/6359816/22268826/d509bf90-e23d-11e6-85c4-76b026758790.png)

When run using RStudio, the label text does not bleed over the labels

That is, if the width of the text is longer than the width of the label box, then the text is cut off. In the examples online, the text extends beyond label box

**Comment by daattali** [comment]
I don't think it "bleeds over" when you're in a browser as well? Whether it does or not is because of CSS - if you want it one way or the other, you need to use a bit of custom CSS (probably something with an "overflow" property). Moreover, if it works in a browser but not in RStudio, then that would be because the rstudio viewer is its own very minimal web browser that has doesn't support many things that real browsers do. If you do find some CSS to make it bleed over like you like, you could post it here for future reference!

**Comment by briglass** [comment]
Thanks for the quick response. I've included a screenshot from the web demo,  you can see that the text extends beyond the label box -- I'd like to replicate this behavior in the R output, as I have long labels
![timevis_bleed2](https://cloud.githubusercontent.com/assets/6359816/22300234/aeeb583e-e2db-11e6-8794-74da44c6a61c.png)

**Comment by daattali** [comment]
Have you tried replicating my code? It's all available on github: https://github.com/daattali/timevis/tree/master/inst/example

If you try running the same code without any custom CSS, you'll see that indeed labels do not bleed over by default. Looks like I used a custom line of CSS to do that. https://github.com/daattali/timevis/blob/master/inst/example/www/style.css#L71

**Comment by briglass** [comment]
Adding that line worked like a charm, thanks!
