### ISSUE TITLE
How do subgroups work? Example would be helpful

### ISSUE THREAD

**Issue by knbknb** [daattali/timevis#56]
The help texts mention a feature `subgroup`, but there is no example that demonstrates how to construct data frames with subgroups, and how to pass them to vis.js.

I have found a post from 2017, ["Subgroups in R timevis" on stackoverflow.com](https://stackoverflow.com/questions/45235338/subgroups-in-r-timevis), but I think it can be even better explained than in that post.

**Comment by thurnherr** [comment]
An example could be extremely helpful. Same for nested groups.

**Comment by daattali** [comment]
There are a very large number of parameters supported by visjs Timeline and since this project (and all my other projects) is unfunded, I couldn't invest the time to translate all their examples into R. If you want an example of how to use subgroups, or any other feature, [this page](https://visjs.org/timeline_examples.html) has many examples, and [this page](https://visjs.org/examples/timeline/groups/subgroups.html) is specifically an example usage of subgroups. 

I would be very happy to accept a PR if someone wanted to add an example of using subgroups to the documentation! Thanks

**Comment by daattali** [comment]
I was looking at the documentation and it's already very large. It's difficult to document everything that the javascript library can do, and it would be redundant as well. I'll add more links in the documentation to defer to the visjs docs, but I can't add too much more documentaiton about every specific feature such as this.
