### ISSUE TITLE
y-position of elements

### ISSUE THREAD

**Issue by wendell-t** [daattali/timevis#73]
The vertical (y) position of timeline elements seems to be dynamic.  That is, when zooming or panning, the vertical position of the elements changes, and they move up or down from previous positions.  It may be a javascript/htmlwidgets 'feature', but is there a way to turn it off?

**Comment by daattali** [comment]
It this happens when panning, then it's definitely a behaviour of the underlying javascript library visjs. You can check [on their docs](http://visjs.org/docs/timeline/) if there's any mention of this behaviour, but it doesn't sound like something they probably have configurable. But it's not a timevis issue.
